version: '3.1'

volumes:
  nextcloud:
  db:

services:
  db:
    image: mysql:8
    container_name: nextcloud-mysql
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/mysql_root_passwd
      - MYSQL_PASSWORD_FILE=/run/secrets/nextcloud_db_passwd
      - MYSQL_DATABASE_FILE=/run/secrets/nextcloud_db_name
      - MYSQL_USER_FILE=/run/secrets/nextcloud_db_user

  app:
    image: nextcloud:16.0.3
    container_name: nextcloud-app
    ports:
      - 8080:80
    links:
      - db
    volumes:
      - nextcloud:/var/www/html
    restart: always
